sudo: required
services:
  - docker

before_install:
  - docker build -t joniamon/docker-react -f Dockerfile.dev .

script:
  - docker run joniamon/docker-react npm run test -- --coverage

before_deploy:
  - echo "------------------------------------"
  - echo "$AWS_ACCESS_KEY"
  - echo "$AWS_SECURE_KEY"
  - echo "------------------------------------"

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-619954865319"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "AKIAZAWBQQSTYVLCD44H"
  secret_access_key: "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"